# Generated by Django 4.1 on 2022-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=50)),
                ('resort_description', models.TextField(max_length=500)),
                ('resort_image', models.ImageField(upload_to='resorts_image/%y')),
            ],
        ),
    ]
